

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def Fibonacci_generator(x):
	numbers = [1, 1]
	while numbers[-1] + numbers[-2] < int(x):
		numbers.append(numbers[-1] + numbers[-2])
	return numbers

if __name__ == '__main__':
	print(sum(Fibonacci_generator(4000000)[2::3]))